apiVersion: v1
kind: Service
metadata:
  name: servers
  namespace: {{NAMESPACE}}
  labels:
    app: servers
spec:
  ports:
  - name: http
    port: 9094
    targetPort: 9094
  selector:
    app: servers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servers
  namespace: {{NAMESPACE}}
  labels:
    app: servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servers
  template:
    metadata:
      labels:
        app: servers
        version: v1
    spec:
      containers:
      - name: servers
        ports:
        - containerPort: 9094
        image: {{PULL_IMAGE}}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
      imagePullSecrets:
      - name: {{PULL_SECRET}}
